apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: db-write-dev
spec:
  destination:
    name: ''
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    path: config/dev
    repoURL: 'https://github.com/lugosidomotor/MLOps_app.git'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
